name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get ctinews2.m3u8
      run: |
        touch ./ctinews2.m3u8
        sudo cat >./ctinews2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=WPfPjbOLNfE)
        EOL
    - name: Get ttvnews.m3u8
      run: |
        touch ./ttvnews.m3u8
        sudo cat >./ttvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL
    - name: Get ftvnews.m3u8
      run: |
        touch ./ftvnews.m3u8
        sudo cat >./ftvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=ylYJSBUgaMA)
        EOL
    - name: Get ctsnews.m3u8
      run: |
        touch ./ctsnews.m3u8
        sudo cat >./ctsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/ctstw/live)
        EOL
    - name: Get ctvnews.m3u8
      run: |
        touch ./ctvnews.m3u8
        sudo cat >./ctvnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/twctvnews/live)
        EOL
    - name: Get setlive.m3u8
      run: |
        touch ./setlive.m3u8
        sudo cat >./setlive.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=jlldIiGA5bU)
        EOL
    - name: Get setinews.m3u8
      run: |
        touch ./setinews.m3u8
        sudo cat >./setinews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/live/CKjSm5ZeehE?feature=share)
        EOL
    - name: Get ebcnews.m3u8
      run: |
        touch ./ebcnews.m3u8
        sudo cat >./ebcnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/newsebc/live)
        EOL
    - name: Get globalnews.m3u8
      run: |
        touch ./globalnews.m3u8
        sudo cat >./globalnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=B7Zp3d6xXWw)
        EOL
    - name: Get tvbs.m3u8
      run: |
        touch ./tvbs.m3u8
        sudo cat >./tvbs.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=2mCSYvcfhtc)
        EOL
    - name: Get ebcfnews.m3u8
      run: |
        touch ./ebcfnews.m3u8
        sudo cat >./ebcfnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/user/57etfn/live)
        EOL
    - name: Get mnews.m3u8
      run: |
        touch ./mnews.m3u8
        sudo cat >./mnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=5n0y6b0Q25o)
        EOL
    - name: Get daaione.m3u8
      run: |
        touch ./daaione.m3u8
        sudo cat >./daaione.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=MIqUplvSRWA)
        EOL
    - name: Get daaitwo.m3u8
      run: |
        touch ./daaitwo.m3u8
        sudo cat >./daaitwo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL
    - name: Get ctsshow.m3u8
      run: |
        touch ./ctsshow.m3u8
        sudo cat >./ctsshow.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/TBSCTSSHOW/live)
        EOL
    - name: Get ebcyoyo.m3u8
      run: |
        touch ./ebcyoyo.m3u8
        sudo cat >./ebcyoyo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g https://www.youtube.com/c/yoyotvebc/live)
        EOL
    - name: Get ctinews.m3u8
      run: |
        touch ./ctinews.m3u8
        sudo cat >./ctinews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=_QbRXRnHMVY)
        EOL
    - name: Get gstv.m3u8
      run: |
        touch ./gstv.m3u8
        sudo cat >./gstv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g https://www.youtube.com/channel/UCoo-jAsJgM8z09ddlhcBlSA/live)
        EOL
    - name: Get parliamentarytv.m3u8
      run: |
        touch ./parliamentarytv.m3u8
        sudo cat >./parliamentarytv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/國會頻道/live)
        EOL
    - name: Get sensengo47.m3u8
      run: |
        touch ./sensengo47.m3u8
        sudo cat >./sensengo47.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=ViJ3XiN6Q3M)
        EOL
    - name: Get sensengo34.m3u8
      run: |
        touch ./sensengo34.m3u8
        sudo cat >./sensengo34.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=_Vlzn9qAHD4)
        EOL
    - name: Get sensengo46
      run: |
        touch ./sensengo46.m3u8
        sudo cat >./sensengo46.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=Z50JFuNgvB0)
        EOL
    - name: Get sensengo60.m3u8
      run: |
        touch ./sensengo60.m3u8
        sudo cat >./sensengo60.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=u0NYyH3ZesE)
        EOL
    - name: Get momoshop1.m3u8
      run: |
        touch ./momoshop1.m3u8
        sudo cat >./momoshop1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=_pZQ1Lk0xMA)
        EOL
    - name: Get momoshop2.m3u8
      run: |
        touch ./momoshop2.m3u8
        sudo cat >./momoshop2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=xbNWkUyxQGM)
        EOL
    - name: Get annnews.m3u8
      run: |
        touch ./annnews.m3u8
        sudo cat >./annnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=coYw-eVU0Ks)
        EOL
    - name: Get tbsnews.m3u8
      run: |
        touch ./tbsnews.m3u8
        sudo cat >./tbsnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/v/H3D90-436C4)
        EOL
    - name: Get nbcnews.m3u8
      run: |
        touch ./nbcnews.m3u8
        sudo cat >./nbcnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/c/nbcnews/live)
        EOL
    - name: Get nbc2news.m3u8
      run: |
        touch ./nbc2news.m3u8
        sudo cat >./nbc2news.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/user/NBC2swfl/live)
        EOL
    - name: Get gbnews.m3u8
      run: |
        touch ./gbnews.m3u8
        sudo cat >./gbnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/GBNewsOnline/live)
        EOL
    - name: Get aljazeera.m3u8
      run: |
        touch ./aljazeera.m3u8
        sudo cat >./aljazeera.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/user/AlJazeeraEnglish/live)
        EOL
    - name: Get trtworld.m3u8
      run: |
        touch ./trtworld.m3u8
        sudo cat >./trtworld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/trtworld/live)
        EOL
    - name: Get france24.m3u8
      run: |
        touch ./france24.m3u8
        sudo cat >./france24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g https://www.youtube.com/user/france24english/live)
        EOL
    - name: Get français24.m3u8
      run: |
        touch ./français24.m3u8
        sudo cat >./français24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g https://www.youtube.com/c/france24/live)
        EOL
    - name: Get euronews.m3u8
      run: |
        touch ./euronews.m3u8
        sudo cat >./euronews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g https://www.youtube.com/c/euronews/live)
        EOL
    - name: Get dwnews.m3u8
      run: |
        touch ./dwnews.m3u8
        sudo cat >./dwnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=540000
        $(yt-dlp -g https://www.youtube.com/c/dwnews/live)
        EOL
    - name: Get hokkaidonews.m3u8
      run: |
        touch ./hokkaidonews.m3u8
        sudo cat >./hokkaidonews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/htbnews/live)
        EOL
    - name: Get yntnews.m3u8
      run: |
        touch ./yntnews.m3u8
        sudo cat >./yntnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/ytnnews24/live)
        EOL
    - name: Get nasaearthview.m3u8
      run: |
        touch ./nasaearthview.m3u8
        sudo cat >./nasaearthview.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=Y1qQZbTF8iQ)
        EOL
    - name: Get spaceviewearth.m3u8
      run: |
        touch ./spaceviewearth.m3u8
        sudo cat >./spaceviewearth.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=86YLFOog4GM)
        EOL
    - name: Get ipanda.m3u8
      run: |
        touch ./ipanda.m3u8
        sudo cat >./ipanda.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=MIA8AKVZ0Yk)
        EOL
    - name: Get kpop.m3u8
      run: |
        touch ./kpop.m3u8
        sudo cat >./kpop.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/thekpop/live)
        EOL
    - name: Get hitfm.m3u8
      run: |
        touch ./hitfm.m3u8
        sudo cat >./hitfm.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/user/hitfm1077/live)
        EOL
    - name: Get cpop.m3u8
      run: |
        touch ./cpop.m3u8
        sudo cat >./cpop.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=wrYF0HX7Kzc)
        EOL
    - name: Get skynews.m3u8
      run: |
        touch ./skynews.m3u8
        sudo cat >./skynews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=9Auq9mYxFEE)
        EOL
    - name: Get nhkworld.m3u8
      run: |
        touch ./nhkworld.m3u8
        sudo cat >./nhkworld.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/nhkworldjapan/live)
        EOL
    - name: Get cgtn.m3u8
      run: |
        touch ./cgtn.m3u8
        sudo cat >./cgtn.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/cgtneurope/live)
        EOL
    - name: Get foxlivenow.m3u8
      run: |
        touch ./foxlivenow.m3u8
        sudo cat >./foxlivenow.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/c/livenowfox/live)
        EOL
    - name: Get jnnnews.m3u8
      run: |
        touch ./jnnnews.m3u8
        sudo cat >./jnnnews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
        $(yt-dlp -g https://www.youtube.com/watch?v=H3D90-436C4)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: ytblive m3u8
        path: .
    - name: Git push assets to "ytblive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b ytblive
        git add .
        git commit -m "Update ytblive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin ytblive
